print('Напешіть свій вік:')
name1 = input()
print('Напешіть як вас звуть:')
name2 = input()
print('Напешіть яка в вас улюблена страва:')
name3 = input()
print("привіт мені")
print(name1)
print('Мене звуть')
print(name2)
print("В мене улюблена страва")
print(name3)
